name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8 mcp_server/ --max-line-length=120
      - name: Run MCP server (run for 1 hour, then stop)
        run: |
          python mcp_server/server.py &
          SERVER_PID=$!
          sleep 3600
          kill $SERVER_PID
      - name: Run tests
        run: |
          echo "No tests yet. Add tests in the tests/ directory."
